### ISSUE TITLE
USER STORY: Tour page

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#1]
As a **shopper** I can **browse tours** so that **I can choose which ones I'd like to purchase**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide a range of tours for users to choose from
- Display tours in an organised manner for a good user experience
- Use anchor tags for the tour titles that are linked to the tour detail pages so it's easy for users to view the tours in more detail

**Comment by tymaestro** [comment]
### Tasks

- [x] Write custom tours to be stored in the database
- [x] Add relevant images so users can get a visual idea about what they will experience on the tour
- [x] Make the tour title a link to the tour detail page so users can view the tour in more detail
- [x] As a superuser, provide functionality to edit and delete tours from the tours page
