### ISSUE TITLE
USER STORY: Add tour

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#11]
As an **administrator** I can **add products to the website** so that **I have new products for customers to purchase**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide CRUD functionality so as the owner of the site, I can make quick and easy changes to the database
- Be able to add tours in both Django admin and on the live site

**Comment by tymaestro** [comment]
### Tasks

- [x] Provide an empty form with the relevant fields for creating a new tour
- [x] Add a button so that as a site owner I can navigate back to the tours page if I choose not to add a tour
- [x] Add a button so that as a site owner I can create the new tour in the database when I have filled out the required fields
