### ISSUE TITLE
USER STORY: Edit tour

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#12]
As an **administrator** I can **edit current tours** so that **I can keep tours up to date if the tours/pricing changes**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide CRUD functionality so as the owner of the site, I can make quick and easy changes to the database
- Be able to edit tours in both Django admin and on the live site

**Comment by tymaestro** [comment]
### Tasks

- [x] Add a form with the fields of the selected tour pre-populated so that as a site owner I can easily edit and update the tour
- [x] Add a button to cancel editing the tour if as a site owner I decide not to update the tour at that moment
- [x] Add a button to update the tour if I have made any changes
- [x] Add models so that some fields are required before a tour is updated
