### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#2]
As a **user** I can **view a clear home page/website** so that **I understand the concept behind the website**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Write clear and concise content on the home page to inform users what the site is about
- Provide users with a link to explore the tours in more detail
- Use a relevant and appealing image to pique the curiosity of visitors to the site

**Comment by tymaestro** [comment]
### Tasks

- [x] Write text that connects the users to the concept of the site
- [x] Add an appealing image that conveys a happy message to the users
- [x] Add a button to guide users to the tours page
