### ISSUE TITLE
USER STORY: Images

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#21]
As a site owner, I want to create a strong identity by adding meaningful images so that customers will be drawn to the site and to the tours on offer

**Comment by tymaestro** [comment]
### Acceptance Criteria

- See a small image of each tour on the tours page so users can correctly choose which tours they would like to view
- See a larger image on the tour detail page to attract users to the chosen tour
- Include relevant and striking images throughout the site to keep users on the site and wanting more new tours

**Comment by tymaestro** [comment]
### Tasks

- [x] Find images to suit the site and relevant tours
- [x] Download the images from a copyright-free image provider (e.g. Pexels)
- [x] Import images into the project environment
- [x] Assign the images to the corresponding tours
