### ISSUE TITLE
EPICS - README file

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#22]
As a developer I want to document the development process so that myself and future developers can quickly acquaint themselves with the project

**Comment by tymaestro** [comment]
### Tasks

- [x] Document features of site and include supporting images
- [x] Manually test the site's features and document the testing process
- [x] Run accessibility reports on each page (e.g. Google lighthouse)
- [x] Include credits and acknowledgements section
- [x] Document the flowchart and ERD of the project
- [x] Document that code is Pep8, JShint and W3C compliant
- [x] Features left to implement
- [x] Business model
- [x] Design process including wireframes
