### ISSUE TITLE
USER STORY: Messages

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#23]
As a site owner, I want to display messages so that users stay informed. As a user, I want to see messages when an action has been taken such as logging in

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Messages are displayed just long enough for users to read them and then they disappear for users to continue enjoying the site

### Tasks

- [x] Import Django messages
- [x] Create Javascript timeout function for messages to disappear after a few seconds
- [x] Format messages to display in a UX friendly manner
- [x] Write informative messages so that users understand what's happening on the site
