### ISSUE TITLE
USER STORY: Sign-up option

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#3]
As a **user** I can **create a secure account** so that **I can purchase items on the website and see my order history**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide a secure method of sign-up so users know their information is safe
- Make sign-up an easy process so users are not daunted by the prospect of creating an account

**Comment by tymaestro** [comment]
### Tasks

- [x] Install allauth to provide users with secure signup and login functionality
- [x] Install crispy forms
- [x] Modify the allauth signup page to provide users with a more UX-friendly form than the default
