### ISSUE TITLE
USER STORY: Tour detail page

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#4]
As a **user** I can **view an individual product** so that **I can see the details, adjust the quantity and add it to my basket**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide the ability to adjust the quantity of tours to be added to the basket
- Provide a detailed description of each tour for users to make an informed choice
- Button to add tour/s to basket

**Comment by tymaestro** [comment]
### Tasks

- [x] Create the view for the tour detail page
- [x] Create the HTML page with relevant content so users can gain more knowledge about each tour
- [x] Add a button to add the given tour to the basket
- [x] Add a button to allow users to navigate back to the tours page if they want to select another tour or add to the ones they've already added to the basket
- [x] Add the functionality to increase or decrease the number of tours a user wants to add to their basket
