### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#5]
As a **user** I can **securely provide personal information including credit card details** so that **I can purchase my products**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide a quick and easy way for customers to checkout
- Provide secure checkout through the use of Stripe as a payment system
- Provide logged in users with a pre-populated checkout form based on the information they have provided to make the checkout process easier

**Comment by tymaestro** [comment]
### Tasks

- [x] Install Stripe and add all relevant public and secret keys as well as the webhook key to settings.py
- [x] Use crispy forms and CSS styling to provide users with a UX-friendly form
- [x] Follow Stripe documentation and add JavaScript for checkout functionality
- [x] Provide users with a summary of their basket so they can see what they are about to purchase without navigating away from the checkout page
- [x] Add a button so users can return to the basket page and add or delete tours
- [x] Install countryfields so users can easily choose a country in the format that conforms with Stripe's codes
- [x] Provide a success message when users make a purchase to confirm that their order has been received
- [x] Send the users to an order summary page after purchase to review the tours they've bought
