### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#7]
As a **user** I can **navigate the website easily** so that **I can find what I'm looking for in an efficient manner**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide a clear and focused navbar with links to relevant pages

**Comment by tymaestro** [comment]
### Tasks

Create a navbar that includes easy access to all parts of the site. These include links to:

- [x] Home page
- [x] Tours page
- [x] Sign-up page
- [x] Sign-in page
- [x] My basket page
- [x] Logout page (logged-in users)
- [x] My profile page (logged-in users)
- [x] Tour management page (restricted to superusers)
