### ISSUE TITLE
USER STORY: Subscribe to newsletter

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/PP5-2022#8]
As a **user** I can **subscribe to the newsletter** so that **I can keep up to date on the latest tours**

**Comment by tymaestro** [comment]
### Acceptance Criteria

- Provide users with a simple way of subscribing to the newsletter
- Have a straightforward form with an email input and subscribe button to make the process as easy as possible

**Comment by tymaestro** [comment]
### Tasks

- [x] Create a form for users to provide their email address so it can be registered in the database
- [x] Add a button so users can users can confirm that they want a subscription
- [x] Add a button so users can return to the tours page if they change their mind about registering for a tour or once they have registered
